export const characters = [
  {
    name: 'Joffreyn',
    family: 'Baratheon',
    age: 30,
    reignYears: 5,
    weapon: 'Espada',
    skill: 'Experto',
    flattery: 'Alto',
    advisorTo: 'Rey X',
    serves: 'Casa Y',
    isAlive: true,
    imageURL: './public/img/joffrey.jpg',
  },
  {
    name: 'Jaime',
    family: 'Lannister',
    age: 30,
    reignYears: 5,
    weapon: 'Espada',
    skill: 'Experto',
    flattery: 'Alto',
    advisorTo: 'Rey X',
    serves: 'Casa Y',
    isAlive: true,
    imageURL: './public/img/jaime.jpg',
  },
  {
    name: 'Daenerys',
    family: 'Targaryen',
    age: 30,
    reignYears: 5,
    weapon: 'Espada',
    skill: 'Experto',
    flattery: 'Alto',
    advisorTo: 'Rey X',
    serves: 'Casa Y',
    isAlive: true,
    imageURL: './public/img/daenerys.jpg',
  },
  {
    name: 'Tyrion',
    family: 'Lannister',
    age: 30,
    reignYears: 5,
    weapon: 'Espada',
    skill: 'Experto',
    flattery: 'Alto',
    advisorTo: 'Rey X',
    serves: 'Casa Y',
    isAlive: true,
    imageURL: './public/img/tyrion.jpg',
  },
  {
    name: 'Bronn',
    family: 'Lannister',
    age: 30,
    reignYears: 5,
    weapon: 'Espada',
    skill: 'Experto',
    flattery: 'Alto',
    advisorTo: 'Rey X',
    serves: 'Casa Y',
    isAlive: true,
    imageURL: './public/img/bronn.jpg',
  },
];
